### ISSUE TITLE
On iOS, the store listing for the app shows as invalid URL Safari (Simulator)

### ISSUE THREAD

**Issue by flutternoob** [Frezyx/open_store#4]
Hi. Thanks for a great library. It works fine on Android. However, on iOS Simulator, the store listing for the app shows as invalid URL in Safari. I suspect this problem to lie with the URL you use in the plugin.

The URL you use is:

https://apps.apple.com/app/idIOS_APP_ID

Whereas, the URL for the iOS App Store listing is:

https://apps.apple.com/app/APP_NAME/idIOS_APP_ID

Error log:

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Error, Error while launching https://apps.apple.com/app/id15********, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      launch (package:url_launcher/src/legacy_api.dart:102:23)
<asynchronous suspension>
#3      OpenStore._opeenCommon (package:open_store/src/open_store/open_store.dart:80:7)
<asynchronous suspension>
```

**Comment by mantreshkhurana** [comment]
I tried this on iOS simulator and it didn't worked, after fixing the url issue it was still not working I printed the url and copied it on my iPhone and it was working.

https://stackoverflow.com/questions/13645554/itunes-app-link-cannot-open-page-in-safari-in-simulator-and-also-idevices
